version: "3.9"

services:
    customer_base_db:
        container_name: customer_base_db
        image: postgres:14-alpine
        ports:
            - 5432:5432
        env_file:
            - ./backend-express/.env

    backend:
        container_name: backend
        build: ./backend-express
        ports:
            - 8000:8000
        env_file:
            - ./backend-express/.env
        depends_on:
            - customer_base_db
        command: bash -c "yarn typeorm migration:run -d src/data-source && yarn dev"

    frontend:
        container_name: frontend
        build: ./frontend
        ports:
            - 3000:3000
        depends_on:
            - backend
